#!/usr/bin/env zsh

# Runtime credentials loader.
#
# Policy:
# - Git identity (MAIN/SUB) is loaded from local file generated by chezmoi.
# - No 1Password dependency.

_dot_has_cmd() {
  command -v "$1" >/dev/null 2>&1
}

_dot_log() {
  [[ "${DOT_CRED_VERBOSE:-0}" == "1" ]] || return 0
  print -r -- "$@" >&2
}

_dot_cred_local_file() {
  print -r -- "${DOT_CRED_LOCAL_FILE:-$HOME/.config/zsh/credentials.local.zsh}"
}

dot-cred-source-local() {
  local f
  f="$(_dot_cred_local_file)"
  if [[ -f "$f" ]]; then
    source "$f"
    return 0
  fi
  return 1
}

dot-cred-refresh() {
  dot-cred-source-local || {
    print -r -- "dot-cred-refresh: local credentials file not found: $(_dot_cred_local_file)" >&2
    print -r -- "dot-cred-refresh: run 'chezmoi apply' or create the file manually." >&2
    return 1
  }
}

dot-cred-status() {
  local f
  f="$(_dot_cred_local_file)"
  print -r -- "DOT_CRED_LOCAL_FILE=$f"
  print -r -- "GIT_MAIN_NAME=${GIT_MAIN_NAME:-}"
  print -r -- "GIT_MAIN_EMAIL=${GIT_MAIN_EMAIL:-}"
  print -r -- "GITHUB_MAIN_USERNAME=${GITHUB_MAIN_USERNAME:-}"
  print -r -- "GIT_SUB_NAME=${GIT_SUB_NAME:-}"
  print -r -- "GIT_SUB_EMAIL=${GIT_SUB_EMAIL:-}"
  print -r -- "GITHUB_SUB_USERNAME=${GITHUB_SUB_USERNAME:-}"
}

_dot_github_main_key_path() {
  print -r -- "${DOT_GITHUB_MAIN_SSH_KEY:-$HOME/.ssh/id_ed25519_github_main}"
}

_dot_github_sub_key_path() {
  print -r -- "${DOT_GITHUB_SUB_SSH_KEY:-$HOME/.ssh/id_ed25519_github_sub}"
}

_dot_ssh_mkdir_and_perms() {
  local dir
  dir="$HOME/.ssh"
  mkdir -p "$dir" || return 1
  chmod 700 "$dir" 2>/dev/null || true
}

_dot_ssh_fix_key_perms() {
  local key="$1"
  chmod 600 "$key" 2>/dev/null || true
  if [[ -f "$key.pub" ]]; then
    chmod 644 "$key.pub" 2>/dev/null || true
  fi
}

dot-github-ssh-key-ensure() {
  # Usage:
  #   dot-github-ssh-key-ensure [--source local|gen] [--force]
  local source force
  source="${DOT_GITHUB_SSH_SOURCE:-auto}"
  force=0

  while [[ $# -gt 0 ]]; do
    case "$1" in
      --source)
        source="$2"; shift 2;;
      --force)
        force=1; shift;;
      -h|--help)
        print -r -- "dot-github-ssh-key-ensure [--source local|gen] [--force]"; return 0;;
      *)
        print -r -- "dot-github-ssh-key-ensure: unknown arg: $1" >&2; return 2;;
    esac
  done

  local key
  key="${DOT_GITHUB_SSH_KEY:-}"
  if [[ -z "$key" ]]; then
    print -r -- "dot-github-ssh-key-ensure: DOT_GITHUB_SSH_KEY is not set (use dot-github-main-ssh-key-ensure or dot-github-sub-ssh-key-ensure)" >&2
    return 2
  fi

  _dot_ssh_mkdir_and_perms || return 1

  if [[ "$source" == "auto" ]]; then
    if [[ -f "$key" ]]; then
      source="local"
    else
      source="gen"
    fi
  fi

  case "$source" in
    local)
      [[ -f "$key" ]] || { print -r -- "SSH key not found: $key" >&2; return 1; }
      _dot_ssh_fix_key_perms "$key"
      ;;
    gen)
      if [[ -f "$key" && "$force" != "1" ]]; then
        _dot_ssh_fix_key_perms "$key"
        return 0
      fi
      _dot_has_cmd ssh-keygen || { print -r -- "ssh-keygen not found" >&2; return 1; }
      local comment
      comment="${GIT_MAIN_EMAIL:-${GIT_SUB_EMAIL:-github}}"
      ssh-keygen -t ed25519 -a 64 -f "$key" -N "" -C "$comment" >/dev/null
      _dot_ssh_fix_key_perms "$key"
      ;;
    *)
      print -r -- "dot-github-ssh-key-ensure: unknown source: $source (expected: local|gen|auto)" >&2
      return 2
      ;;
  esac

  if [[ ! -f "$key.pub" ]] && _dot_has_cmd ssh-keygen; then
    ssh-keygen -y -f "$key" >| "$key.pub" 2>/dev/null || true
    _dot_ssh_fix_key_perms "$key"
  fi
}

dot-github-main-ssh-key-ensure() {
  DOT_GITHUB_SSH_KEY="$(_dot_github_main_key_path)" dot-github-ssh-key-ensure "$@"
}

dot-github-sub-ssh-key-ensure() {
  DOT_GITHUB_SSH_KEY="$(_dot_github_sub_key_path)" dot-github-ssh-key-ensure "$@"
}

dot-github-ssh-pubkey() {
  local key
  key="${DOT_GITHUB_SSH_KEY:-}"
  if [[ -z "$key" ]]; then
    print -r -- "dot-github-ssh-pubkey: set DOT_GITHUB_SSH_KEY or use dot-github-main-ssh-pubkey/dot-github-sub-ssh-pubkey" >&2
    return 2
  fi
  [[ -f "$key" ]] || { print -r -- "SSH key not found: $key" >&2; return 1; }
  if [[ -f "$key.pub" ]]; then
    cat "$key.pub"
    return 0
  fi
  _dot_has_cmd ssh-keygen || { print -r -- "ssh-keygen not found" >&2; return 1; }
  ssh-keygen -y -f "$key"
}

dot-github-main-ssh-pubkey() {
  DOT_GITHUB_SSH_KEY="$(_dot_github_main_key_path)" dot-github-ssh-pubkey
}

dot-github-sub-ssh-pubkey() {
  DOT_GITHUB_SSH_KEY="$(_dot_github_sub_key_path)" dot-github-ssh-pubkey
}
